version: '3.8'
services:
    frontend:
        build: .
        container_name: family_flavors_app
        ports:
            - '3000:3000'
        volumes:
            - ./:/app
        stdin_open: true
        tty: true
